#!/usr/bin/env python3
"""Generate the committed ParseHawk OpenAPI contract from FastAPI."""

from __future__ import annotations

import argparse
import difflib
from pathlib import Path
from typing import Any

import yaml

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPOSITORY_ROOT / "openapi" / "openapi.yaml"
GENERATED_HEADER = (
    "# Generated by `just openapi-export`; do not edit by hand.\n"
    "# FastAPI routes and Pydantic models are the source of truth.\n"
)


def build_openapi_document() -> dict[str, Any]:
    """Return the public OpenAPI document generated by the application."""
    from parsehawk.server.api.fastapi.app import app

    return app.openapi()


def render_openapi_yaml(document: dict[str, Any]) -> str:
    """Serialize the document deterministically for useful review diffs."""
    rendered = yaml.safe_dump(
        document,
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
        width=100,
    )
    return f"{GENERATED_HEADER}{rendered}"


def check_output(output_path: Path, expected: str) -> int:
    """Return non-zero and print a diff when the committed artifact drifted."""
    if not output_path.exists():
        print(f"OpenAPI artifact is missing: {output_path.relative_to(REPOSITORY_ROOT)}")
        print("Run `just openapi-export` and commit the result.")
        return 1

    actual = output_path.read_text(encoding="utf-8")
    if actual == expected:
        print("OpenAPI artifact is in sync with FastAPI.")
        return 0

    relative = output_path.relative_to(REPOSITORY_ROOT)
    print(f"OpenAPI artifact is stale: {relative}")
    print("Run `just openapi-export` and commit the result.\n")
    print(
        "".join(
            difflib.unified_diff(
                actual.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=str(relative),
                tofile=f"generated/{relative}",
            )
        ),
        end="",
    )
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="output path (default: openapi/openapi.yaml)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed artifact without modifying the working tree",
    )
    args = parser.parse_args()

    output_path = args.output.resolve()
    rendered = render_openapi_yaml(build_openapi_document())
    if args.check:
        return check_output(output_path, rendered)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(rendered, encoding="utf-8")
    print(f"Wrote {output_path.relative_to(REPOSITORY_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
