"""Provision and launch vLLM in a dedicated, isolated environment.

vLLM is a heavyweight server whose dependency tree (modern fastapi/starlette,
flashinfer, torch) conflicts with ParseHawk's own app environment. Rather than
co-resolving the two — which downgrades one to break the other — vLLM lives in
its own ``uv`` venv. Two real-world papercuts are smoothed over here so that
``parsehawk start`` is turnkey on a bare GPU host:

* vLLM's bundled ``prometheus-fastapi-instrumentator`` crashes on Starlette 1.x
  routes (``_IncludedRouter`` has no ``path``), 500-ing every request. We install
  a ``.pth`` hook that patches the offending lookup in every interpreter the venv
  starts (the API process *and* its spawned engine workers).
* vLLM's FlashInfer sampler JIT-compiles a CUDA kernel at runtime, which needs a
  build toolchain (``ninja``/``nvcc``) that GPU images don't always ship. We set
  ``VLLM_USE_FLASHINFER_SAMPLER=0`` (see ``vllm_launch_env``) to use the native
  PyTorch sampler instead.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
from collections.abc import Callable
from pathlib import Path

PATCH_MODULE_NAME = "_parsehawk_vllm_patch"

_PATCH_SOURCE = """\
# Auto-generated by ParseHawk. Makes prometheus-fastapi-instrumentator tolerate
# Starlette 1.x routes so vLLM's metrics middleware does not 500 every request.
try:
    import prometheus_fastapi_instrumentator.routing as _routing

    _original = _routing._get_route_name

    def _safe_get_route_name(scope, routes):
        try:
            return _original(scope, routes)
        except AttributeError:
            return None

    _routing._get_route_name = _safe_get_route_name
except Exception:
    pass
"""


def vllm_launch_env(*, metal_memory_fraction: float | None = None) -> dict[str, str]:
    """Environment overrides required to launch vLLM on a bare GPU host."""
    env = {"VLLM_USE_FLASHINFER_SAMPLER": "0"}
    if metal_memory_fraction is not None:
        env["VLLM_METAL_MEMORY_FRACTION"] = str(metal_memory_fraction)
    return env


# The upstream vllm-metal releases ship a single cp312 wheel, so the Metal
# venv's Python is fixed independently of the (configurable) Linux venv Python.
VLLM_METAL_PYTHON_VERSION = "3.12"


def vllm_metal_wheel_url(version: str) -> str:
    return (
        "https://github.com/vllm-project/vllm-metal/releases/download/"
        f"v{version}/vllm_metal-{version}-cp312-cp312-macosx_11_0_arm64.whl"
    )


def ensure_vllm_metal_venv(
    runtime_home: Path,
    *,
    vllm_version: str,
    vllm_metal_version: str,
    log: Callable[[str], None] = print,
) -> Path:
    """Ensure a pinned vLLM Metal environment exists for macOS Apple Silicon.

    The upstream ``install.sh`` is a moving target: it installs whatever
    vllm-metal wheel is the *latest* GitHub release, against whatever vLLM
    version the script pins on ``main`` that day. ParseHawk instead replicates
    the installer's steps with pinned versions so every install is
    reproducible: build the pinned vLLM source release (with its CPU
    requirements set), then install the vllm-metal wheel from the matching
    release tag. The marker records the pin, so bumping either version
    rebuilds the venv.

    Escape hatches, both of which bypass the pin and leave the environment
    user-managed: ``PARSEHAWK_VLLM_METAL_PYTHON`` points at an explicit
    interpreter, and an existing upstream default environment
    (``~/.venv-vllm-metal``) is reused to avoid a duplicate multi-GB install.
    """
    configured_python = os.getenv("PARSEHAWK_VLLM_METAL_PYTHON")
    if configured_python:
        return Path(configured_python).expanduser()

    upstream_python = Path.home() / ".venv-vllm-metal" / "bin" / "python"
    if upstream_python.exists():
        return upstream_python

    venv_dir = runtime_home / ".venv-vllm-metal"
    python_bin = venv_dir / "bin" / "python"
    marker = runtime_home / ".parsehawk-ready"
    spec = f"vllm=={vllm_version} vllm-metal=={vllm_metal_version}"
    if (
        python_bin.exists()
        and marker.exists()
        and marker.read_text(encoding="utf-8").strip() == spec
    ):
        return python_bin

    uv = shutil.which("uv")
    if uv is None:
        raise SystemExit(
            "`uv` is required to provision the vLLM Metal runtime but was not found on PATH."
        )
    if shutil.which("curl") is None:
        raise SystemExit(
            "`curl` is required to download the vLLM source release but was not found on PATH."
        )

    runtime_home.mkdir(parents=True, exist_ok=True)
    log(
        f"Setting up the vLLM Metal runtime in {venv_dir} "
        f"({spec}; first run can take several minutes)..."
    )
    subprocess.run(
        [uv, "venv", "--clear", "--python", VLLM_METAL_PYTHON_VERSION, "--seed", str(venv_dir)],
        check=True,
    )

    with tempfile.TemporaryDirectory() as tmp:
        tarball = f"vllm-{vllm_version}.tar.gz"
        source_url = (
            f"https://github.com/vllm-project/vllm/releases/download/v{vllm_version}/{tarball}"
        )
        subprocess.run(["curl", "-fsSL", source_url, "-o", tarball], cwd=tmp, check=True)
        subprocess.run(["tar", "xf", tarball], cwd=tmp, check=True)
        source_dir = Path(tmp) / f"vllm-{vllm_version}"
        # unsafe-best-match lets uv resolve the CPU torch builds across the
        # extra indexes listed in the requirements set, as upstream does.
        subprocess.run(
            [
                uv,
                "pip",
                "install",
                "--python",
                str(python_bin),
                "-r",
                "requirements/cpu.txt",
                "--index-strategy",
                "unsafe-best-match",
            ],
            cwd=source_dir,
            check=True,
        )
        subprocess.run(
            [uv, "pip", "install", "--python", str(python_bin), "."],
            cwd=source_dir,
            env={**os.environ, "CXXFLAGS": "-Wno-parentheses"},
            check=True,
        )

    subprocess.run(
        [
            uv,
            "pip",
            "install",
            "--python",
            str(python_bin),
            vllm_metal_wheel_url(vllm_metal_version),
        ],
        check=True,
    )
    marker.write_text(f"{spec}\n", encoding="utf-8")
    return python_bin


def ensure_vllm_venv(
    venv_dir: Path,
    *,
    pip_spec: str,
    python_version: str,
    log: Callable[[str], None] = print,
) -> Path:
    """Ensure an isolated venv with vLLM + the metrics patch exists.

    Returns the path to the venv's Python interpreter. The (slow) create+install
    runs once and is cached; a marker records the installed spec so a changed
    ``pip_spec`` triggers a rebuild.
    """
    python_bin = venv_dir / "bin" / "python"
    marker = venv_dir / ".parsehawk-ready"
    if (
        python_bin.exists()
        and marker.exists()
        and marker.read_text(encoding="utf-8").strip() == pip_spec
    ):
        _write_patch(venv_dir)
        return python_bin

    uv = shutil.which("uv")
    if uv is None:
        raise SystemExit(
            "`uv` is required to provision the vLLM runtime but was not found on PATH."
        )

    log(f"Setting up the vLLM runtime in {venv_dir} (first run; this can take several minutes)...")
    venv_dir.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run([uv, "venv", "--python", python_version, str(venv_dir)], check=True)
    subprocess.run([uv, "pip", "install", "--python", str(python_bin), pip_spec], check=True)
    _write_patch(venv_dir)
    marker.write_text(pip_spec, encoding="utf-8")
    return python_bin


def _write_patch(venv_dir: Path) -> None:
    matches = sorted(venv_dir.glob("lib/python*/site-packages"))
    if not matches:
        raise SystemExit(f"could not locate site-packages in {venv_dir}")
    site_packages = matches[0]
    (site_packages / f"{PATCH_MODULE_NAME}.py").write_text(_PATCH_SOURCE, encoding="utf-8")
    (site_packages / f"{PATCH_MODULE_NAME}.pth").write_text(
        f"import {PATCH_MODULE_NAME}\n", encoding="utf-8"
    )
