#!/usr/bin/env python3
"""Generate CLI, configuration, and extraction-schema references from source."""

from __future__ import annotations

import argparse
import difflib
import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterator

from pydantic_core import PydanticUndefined

from parsehawk.cli.main import (
    CLI_CONFIG_DESCRIPTIONS,
    CONFIG_ENV_OVERRIDES,
    DEFAULT_CLI_CONFIG,
    build_parser,
)
from parsehawk.config import Settings

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
REFERENCE_ROOT = REPOSITORY_ROOT / "apps" / "docs" / "src" / "content" / "docs" / "reference"
CLI_OUTPUT = REFERENCE_ROOT / "cli.md"
CONFIG_OUTPUT = REFERENCE_ROOT / "configuration.md"
EXTRACTION_SCHEMA_SOURCE = (
    REPOSITORY_ROOT / "docs" / "schemas" / "parsehawk-extraction-schema.schema.json"
)
EXTRACTION_SCHEMA_OUTPUT = REFERENCE_ROOT / "extraction-schema.md"
GENERATED_NOTICE = "<!-- Generated by `just references-export`; do not edit by hand. -->"


@dataclass(frozen=True)
class Command:
    parser: argparse.ArgumentParser
    aliases: tuple[str, ...] = ()


def _build_deterministic_parser() -> argparse.ArgumentParser:
    """Build CLI metadata without inheriting a developer's API URL override."""
    previous = os.environ.pop("PARSEHAWK_API_URL", None)
    try:
        return build_parser()
    finally:
        if previous is not None:
            os.environ["PARSEHAWK_API_URL"] = previous


def iter_commands(parser: argparse.ArgumentParser) -> Iterator[Command]:
    """Yield each canonical command once while retaining its aliases."""
    yield Command(parser=parser)
    for action in parser._actions:
        if not isinstance(action, argparse._SubParsersAction):
            continue

        grouped: dict[int, tuple[argparse.ArgumentParser, list[str]]] = {}
        for name, child in action.choices.items():
            entry = grouped.setdefault(id(child), (child, []))
            entry[1].append(name)
        for child, names in grouped.values():
            yield Command(parser=child, aliases=tuple(names[1:]))
            yield from list(iter_commands(child))[1:]


def _argument_syntax(action: argparse.Action) -> str:
    if action.option_strings:
        if action.nargs == 0:
            return ", ".join(f"`{option}`" for option in action.option_strings)
        metavar = action.metavar or action.dest.upper()
        return ", ".join(f"`{option} {metavar}`" for option in action.option_strings)

    metavar = str(action.metavar or action.dest)
    if action.nargs == "?":
        metavar = f"[{metavar}]"
    elif action.nargs == "*":
        metavar = f"[{metavar} ...]"
    elif action.nargs == "+":
        metavar = f"{metavar} [{metavar} ...]"
    return f"`{metavar}`"


def _is_required(parser: argparse.ArgumentParser, action: argparse.Action) -> str:
    for group in parser._mutually_exclusive_groups:
        if action in group._group_actions and group.required:
            return "One of group"
    if action.option_strings:
        return "Yes" if action.required else "No"
    return "No" if action.nargs in {"?", "*"} else "Yes"


def _stable_value(value: Any) -> str:
    if value is None or value is PydanticUndefined or value == argparse.SUPPRESS:
        return "—"
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    if isinstance(value, Path):
        try:
            value = Path("~") / value.relative_to(Path.home())
        except ValueError:
            pass
    if isinstance(value, (list, tuple, dict)):
        value = json.dumps(value, ensure_ascii=False, sort_keys=True)
    elif value == "":
        value = '""'
    return f"`{value}`"


def _table_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def _action_description(action: argparse.Action) -> str:
    description = action.help or ""
    if action.choices is not None:
        choices = ", ".join(f"`{choice}`" for choice in action.choices)
        description = f"{description} Choices: {choices}."
    return _table_cell(description)


def _usage(parser: argparse.ArgumentParser) -> str:
    usage = parser.format_usage().strip()
    return " ".join(usage.removeprefix("usage: ").split())


def render_cli_reference() -> str:
    """Render every argparse command and option as stable Markdown."""
    commands = list(iter_commands(_build_deterministic_parser()))
    lines = [
        "---",
        "title: CLI reference",
        "description: Every ParseHawk command, argument, option, and default generated from argparse.",
        "sidebar:",
        "  order: 2",
        "  badge:",
        "    text: Generated",
        "    variant: success",
        "editUrl: false",
        "---",
        "",
        GENERATED_NOTICE,
        "",
        "This page is generated from the same `argparse` definitions used by the installed",
        "`parsehawk` command. Change CLI help in code, run `just references-export`, and commit",
        "the updated page.",
        "",
        "## Command index",
        "",
    ]
    for command in commands:
        label = command.parser.prog
        anchor = label.lower().replace(" ", "-")
        lines.append(f"- [`{label}`](#{anchor})")

    for command in commands:
        parser = command.parser
        lines.extend(["", f"## {parser.prog}", "", parser.description or "", ""])
        if command.aliases:
            aliases = ", ".join(f"`{alias}`" for alias in command.aliases)
            lines.extend([f"Aliases: {aliases}", ""])
        lines.extend(["```console", f"$ {_usage(parser)}", "```", ""])

        actions = [
            action
            for action in parser._actions
            if not isinstance(action, argparse._SubParsersAction)
        ]
        if not actions:
            lines.append("This command has no arguments or options.")
            continue

        lines.extend(
            [
                "| Argument | Description | Required | Default |",
                "| --- | --- | --- | --- |",
            ]
        )
        for action in actions:
            lines.append(
                "| "
                + " | ".join(
                    [
                        _argument_syntax(action),
                        _action_description(action),
                        _is_required(parser, action),
                        _stable_value(action.default),
                    ]
                )
                + " |"
            )
    return "\n".join(lines).rstrip() + "\n"


def _schema_type(schema: dict[str, Any]) -> str:
    if "anyOf" in schema:
        types = [_schema_type(option) for option in schema["anyOf"]]
        return " or ".join(dict.fromkeys(types))
    schema_type = schema.get("type", "value")
    if schema_type == "null":
        return "null"
    return str(schema_type)


def _constraints(schema: dict[str, Any]) -> str:
    labels = {
        "minimum": "minimum",
        "exclusiveMinimum": "greater than",
        "maximum": "maximum",
        "exclusiveMaximum": "less than",
        "minLength": "minimum length",
        "maxLength": "maximum length",
    }
    values = [f"{label} `{schema[key]}`" for key, label in labels.items() if key in schema]
    return "; ".join(values)


def _field_default(name: str) -> Any:
    field = Settings.model_fields[name]
    return field.get_default(call_default_factory=True)


def render_configuration_reference() -> str:
    """Render environment and persistent CLI settings from typed source metadata."""
    settings_schema = Settings.model_json_schema(mode="validation")
    properties = settings_schema["properties"]
    lines = [
        "---",
        "title: Configuration reference",
        "description: Environment variables and persistent CLI settings generated from typed source metadata.",
        "sidebar:",
        "  order: 3",
        "  badge:",
        "    text: Generated",
        "    variant: success",
        "editUrl: false",
        "---",
        "",
        GENERATED_NOTICE,
        "",
        "ParseHawk service settings are typed with Pydantic and use the `PARSEHAWK_` prefix.",
        "Values are read when each process starts.",
        "",
        "## Service environment variables",
        "",
        "| Environment variable | Type | Default | Description |",
        "| --- | --- | --- | --- |",
    ]

    for name, field in Settings.model_fields.items():
        schema = properties[name]
        env_name = f"PARSEHAWK_{name.upper()}"
        description = field.description or ""
        constraints = _constraints(schema)
        if constraints:
            description = f"{description} Constraint: {constraints}."
        if schema.get("writeOnly"):
            description = f"{description} Sensitive value; never expose it in logs or docs."
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{env_name}`",
                    _schema_type(schema),
                    _stable_value(_field_default(name)),
                    _table_cell(description),
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Persistent CLI configuration",
            "",
            "The CLI stores explicitly set values in `~/.parsehawk/config.json`. Override that",
            "location with `PARSEHAWK_CONFIG_PATH`. Environment overrides take precedence when",
            "the relevant command loads effective CLI configuration.",
            "",
            "| Key | Environment override | Default | Description |",
            "| --- | --- | --- | --- |",
        ]
    )
    for key, default in DEFAULT_CLI_CONFIG.items():
        if key == "data.dir" and default == "":
            rendered_default = "`./data` in a source checkout; otherwise `~/.parsehawk/data`"
        else:
            rendered_default = _stable_value(default)
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{key}`",
                    f"`{CONFIG_ENV_OVERRIDES[key]}`",
                    rendered_default,
                    _table_cell(CLI_CONFIG_DESCRIPTIONS[key]),
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Cross-cutting environment controls",
            "",
            "| Environment variable | Purpose |",
            "| --- | --- |",
            "| `PARSEHAWK_CONFIG_PATH` | Override the persistent CLI configuration file path. |",
            "| `DO_NOT_TRACK` | Disable anonymous telemetry when set to a truthy value. |",
            "| `OTEL_SDK_DISABLED` | Disable OpenTelemetry export when set to `true`. |",
            "| `OTEL_EXPORTER_OTLP_ENDPOINT` | Send traces to an external OTLP endpoint. |",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def render_extraction_schema_reference() -> str:
    """Render the supported authoring dialect from its canonical meta-schema."""
    schema = json.loads(EXTRACTION_SCHEMA_SOURCE.read_text(encoding="utf-8"))
    definitions = schema["$defs"]
    semantic_values = definitions["parsehawkExtension"]["properties"]["semantic"]["enum"]
    semantic_rows = [
        ("Text", ["string", "verbatim-string"]),
        ("Scalar", ["integer", "number", "boolean"]),
        ("Date and time", ["date", "time", "date-time", "duration"]),
        ("Locale", ["country", "currency", "language", "language-tag", "script"]),
        ("Identifiers", ["url", "email-address", "phone-number", "iban", "bic", "unit-code"]),
        ("Regions", [value for value in semantic_values if value.startswith("region:")]),
    ]
    rendered_semantics = {value for _, values in semantic_rows for value in values}
    if rendered_semantics != set(semantic_values):
        missing = sorted(set(semantic_values) - rendered_semantics)
        extra = sorted(rendered_semantics - set(semantic_values))
        raise ValueError(f"Semantic reference groups are stale (missing={missing}, extra={extra})")

    lines = [
        "---",
        "title: Extraction schema reference",
        "description: The JSON Schema authoring dialect ParseHawk accepts, generated from its canonical meta-schema.",
        "sidebar:",
        "  order: 4",
        "  badge:",
        "    text: Generated",
        "    variant: success",
        "editUrl: false",
        "---",
        "",
        GENERATED_NOTICE,
        "",
        "ParseHawk accepts a focused JSON Schema Draft 2020-12 authoring dialect. The",
        "dialect is intentionally smaller than general JSON Schema so an extractor can turn",
        "the same contract into model guidance, output validation, and typed downstream data.",
        "",
        "[Download the canonical meta-schema](/schemas/parsehawk-extraction-schema.schema.json)",
        "or validate a file with `parsehawk schemas validate schema.json`.",
        "",
        "## Supported shapes",
        "",
        "| Shape | Supported authoring fields |",
        "| --- | --- |",
        "| Object | `type`, `properties`, `required`, `additionalProperties`, `title`, `description` |",
        "| Array | `type`, `items`, `title`, `description` |",
        "| String | `type`, `pattern`, `minLength`, `maxLength`, `title`, `description` |",
        "| Number, integer, boolean | `type`, `title`, `description` |",
        "| Enum | `type`, `enum`, optional `x-parsehawk`, `title`, `description` |",
        "| Enum union | `oneOf` or `anyOf` branches containing `const` or `enum` |",
        '| Nullable value | A two-item type union such as `["string", "null"]` |',
        "",
        "The root must be an object with `type` and `properties`. Object schemas must set",
        "`additionalProperties` to `false`. Unknown schema keywords are rejected.",
        "",
        "## Minimal schema",
        "",
        "```json",
        "{",
        '  "$schema": "https://json-schema.org/draft/2020-12/schema",',
        '  "type": "object",',
        '  "properties": {',
        '    "invoice_number": {',
        '      "type": ["string", "null"],',
        '      "description": "The invoice number exactly as printed."',
        "    },",
        '    "total": {',
        '      "type": ["number", "null"],',
        '      "description": "The final amount due."',
        "    }",
        "  },",
        '  "required": ["invoice_number", "total"],',
        '  "additionalProperties": false',
        "}",
        "```",
        "",
        "## Semantic hints",
        "",
        "Set `x-parsehawk.semantic` on a string field to express the value's meaning more",
        "precisely than JSON Schema's primitive type. These hints guide compatible models;",
        "the JSON output still uses ordinary strings, numbers, integers, or booleans.",
        "",
        "| Family | Values |",
        "| --- | --- |",
    ]
    for family, values in semantic_rows:
        lines.append(f"| {family} | {', '.join(f'`{value}`' for value in values)} |")

    lines.extend(
        [
            "",
            "```json",
            "{",
            '  "type": ["string", "null"],',
            '  "description": "Invoice date in ISO 8601 format.",',
            '  "x-parsehawk": { "semantic": "date" }',
            "}",
            "```",
            "",
            "## Source of truth",
            "",
            "The canonical meta-schema is committed at",
            "`docs/schemas/parsehawk-extraction-schema.schema.json`. The generated page and",
            "download endpoint are checked for drift in pre-commit and CI.",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def _check_output(path: Path, expected: str) -> bool:
    if not path.exists():
        print(f"Generated reference is missing: {path.relative_to(REPOSITORY_ROOT)}")
        return False
    actual = path.read_text(encoding="utf-8")
    if actual == expected:
        print(f"Reference is in sync: {path.relative_to(REPOSITORY_ROOT)}")
        return True

    relative = path.relative_to(REPOSITORY_ROOT)
    print(f"Generated reference is stale: {relative}")
    print(
        "".join(
            difflib.unified_diff(
                actual.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=str(relative),
                tofile=f"generated/{relative}",
            )
        ),
        end="",
    )
    return False


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify committed references without modifying the working tree",
    )
    args = parser.parse_args()

    outputs = {
        CLI_OUTPUT: render_cli_reference(),
        CONFIG_OUTPUT: render_configuration_reference(),
        EXTRACTION_SCHEMA_OUTPUT: render_extraction_schema_reference(),
    }
    if args.check:
        return 0 if all(_check_output(path, content) for path, content in outputs.items()) else 1

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"Wrote {path.relative_to(REPOSITORY_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
